obj_shop.show					= false;
obj_shop.show_mini				= false;
obj_inventory.show				= false;
obj_inventory.show_mini			= false;
obj_inventory.show_mini_mini	= false;
obj_library.show				= false;
obj_map.show					= true;
obj_map.show_mini				= false;
merchant_show(undefined, undefined, "travel");