/// @param unicode

switch (argument0) {
	case ord("Q"):		return "Q";
	case ord("W"):		return "W";
	case ord("E"):		return "E";
	case ord("R"):		return "R";
	case ord("T"):		return "T";
	case ord("Y"):		return "Y";
	case ord("U"):		return "U";
	case ord("I"):		return "I";
	case ord("O"):		return "O";
	case ord("P"):		return "P";
	case ord("A"):		return "A";
	case ord("S"):		return "S";
	case ord("D"):		return "D";
	case ord("F"):		return "F";
	case ord("G"):		return "G";
	case ord("H"):		return "H";
	case ord("J"):		return "J";
	case ord("K"):		return "K";
	case ord("L"):		return "L";
	case ord("Z"):		return "Z";
	case ord("X"):		return "X";
	case ord("C"):		return "C";
	case ord("V"):		return "V";
	case ord("B"):		return "B";
	case ord("N"):		return "N";
	case ord("M"):		return "M";
	case vk_left:		return "Left Arrow";
	case vk_right:		return "Right Arrow";
	case vk_up:			return "Up Arrow";
	case vk_down:		return "Down Arrow";
	case vk_space:		return "Spacebar";
	case ord("0"):		return "0";
	case ord("1"):		return "1";
	case ord("2"):		return "2";
	case ord("3"):		return "3";
	case ord("4"):		return "4";
	case ord("5"):		return "5";
	case ord("6"):		return "6";
	case ord("7"):		return "7";
	case ord("8"):		return "8";
	case ord("9"):		return "9";
	case 161:			return "Right Shift";
	case 160:			return "Left Shift";
	case 91:			return "Right Command";
	case 92:			return "Left Command";
	case 164:			return "Left Alt";
	case 165:			return "Right Alt";
	case 162:			return "Left Ctrl";
	case gp_padl:		return "Dpad Left";
	case gp_padr:		return "Dpad Right";
	case gp_padu:		return "Dpad Up";
	case gp_padd:		return "Dpad Down";
	case gp_face3:		return "Left Face Button";
	case gp_face2:		return "Right Face Button";
	case gp_face4:		return "Up Face Button";
	case gp_face1:		return "Down Face Button";
	case gp_shoulderl:	return "Left Bumper";
	case gp_shoulderlb:	return "Left Trigger";
	case gp_shoulderr:	return "Right Bumper";
	case gp_shoulderrb:	return "Right Trigger";
	case gp_start:		return "Start";
	case gp_select:		return "Select";
	case gp_stickl:		return "Left Stick Click";
	case gp_stickr:		return "Right Stick Click";
	case mb_left:		return "Left Mouse";
	case mb_right:		return "Right Mouse";
	case mb_middle:		return "Middle Mouse";
	default:			return string(argument0);	
}