obj_shop.show					= true;
obj_shop.show_mini				= false;
obj_inventory.show				= false;
obj_inventory.show_mini			= false;
obj_inventory.show_mini_mini	= false;
obj_library.show				= false;
obj_map.show					= false;
obj_map.show_mini				= false;
obj_merchant.shop_text = "What can I get for ya?";
merchant_show(undefined, undefined, "buy");